[config]
backup = true
banner = true
create = true
dotpath = ""
keepdot = false
link_dotfile_default = "nolink"
link_on_import = "nolink"
longkey = false

[dotfiles.d_hypr]
src = "config/hypr"
dst = "~/.config/hypr"

[dotfiles.d_alacritty]
src = "config/alacritty"
dst = "~/.config/alacritty"

[dotfiles.d_btop]
src = "config/btop"
dst = "~/.config/btop"

[dotfiles.d_fish]
src = "config/fish"
dst = "~/.config/fish"

[dotfiles.d_i3]
src = "config/i3"
dst = "~/.config/i3"

[dotfiles."f_kvantum.kvconfig"]
src = "config/Kvantum/kvantum.kvconfig"
dst = "~/.config/Kvantum/kvantum.kvconfig"

[dotfiles.d_walker]
src = "config/walker"
dst = "~/.config/walker"

[dotfiles.d_waybar]
src = "config/waybar"
dst = "~/.config/waybar"

[dotfiles.d_spicetify]
src = "config/spicetify"
dst = "~/.config/spicetify"
chmod = "700"

[dotfiles.d_yazi]
src = "config/yazi"
dst = "~/.config/yazi"

[dotfiles.d_fastfetch]
src = "config/fastfetch"
dst = "~/.config/fastfetch"
chmod = "744"

[dotfiles.d_flavours]
src = "config/flavours"
dst = "~/.config/flavours"

[dotfiles.d_micro]
src = "config/micro"
dst = "~/.config/micro"

[dotfiles.d_vesktop]
src = "config/vesktop"
dst = "~/.config/vesktop"
chmod = "700"
instignore = ["*", "!settings/", "!themes/"]
upignore = ["*", "!settings/", "!themes/"]
cmpignore = ["*", "!settings/", "!themes/"]

[dotfiles.d_wezterm]
src = "config/wezterm"
dst = "~/.config/wezterm"

[dotfiles."f_brave-flags.conf"]
src = "config/brave-flags.conf"
dst = "~/.config/brave-flags.conf"

[profiles.offeex-pc]
dotfiles = [
    "d_hypr",
    "d_alacritty",
    "d_btop",
    "d_fish",
    "d_i3",
    "f_kvantum.kvconfig",
    "d_walker",
    "d_waybar",
    "d_spicetify",
    "d_yazi",
    "d_fastfetch",
    "d_flavours",
    "d_micro",
    "d_vesktop",
    "d_wezterm",
    "f_brave-flags.conf",
]
